# Generated by Django 4.2.6 on 2023-11-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('microchip', models.CharField(max_length=30)),
                ('atencion', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=30)),
                ('diagnostico', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoVetChristopher.tratamientos')),
            ],
        ),
    ]
